### ISSUE TITLE
go mod tidy doesnt work if code is in src folder (cant find go.mod)

### ISSUE THREAD

**Issue by rupamkhaitan** [dnephin/pre-commit-golang#51]
I have a root project where all my go code is inside sub-folder src directory and i need to run go mod tidy from top level .pre-commit-config.yaml (cause i believe there is no way to pass args)

Now My pre-commit config file has mentioned the files path (where my sub-folder src/go.mod file reside.. but still go mod tidy always show pass, doesn't do anything by downloading all missing package)

```
- repo: git://github.com/dnephin/pre-commit-golang
  rev: master
  hooks:
    - id: go-mod-tidy
      name:go-mod-tidy
      files: 'src/.*\.go'
```
