### ISSUE TITLE
Can't find `go-mod-tidy` on Windows

### ISSUE THREAD

**Issue by echarrod** [dnephin/pre-commit-golang#52]
I have the following `.pre-commit-config.yaml`:

```yaml
repos:
- repo: git://github.com/dnephin/pre-commit-golang
  rev: master
  hooks:
    - id: go-vet
    - id: go-mod-tidy
```

When I try to run `pre-commit run --all-files` I get:
> [ERROR] `go-mod-tidy` is not present in repository git://github.com/dnephin/pre-commit-golang.  Typo? Perhaps it is introduced in a newer version?  Often `pre-commit autoupdate` fixes this.

` pre-commit autoupdate` won't work whilst `go-mod-tidy` is in the file:
> Updating git://github.com/dnephin/pre-commit-golang ... Cannot update because the tip of HEAD is missing these hooks:
go-mod-tidy

So, after removing `go-mod-tidy`:
> Updating git://github.com/dnephin/pre-commit-golang ... updating master -> v0.3.5.

But when I add `go-mod-tidy` back in again, the same error is present, and it cannot be found.

I am on Windows, I'm not sure whether this affects anything. I've tried uninstalling and reinstalling the hooks too.
